services:
    
  db:
    image: postgres
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - psql:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST=${DATABASE_HOST}
      - POSTGRES_PORT=${DATABASE_PORT}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
  
  api:
    build:
      context: ./api
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
      - 6900:6900
    environment:
      - DEBUG=True
      - POSTGRES_HOST=${DATABASE_HOST}
      - POSTGRES_NAME=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    depends_on:
      - db
    volumes:
      - ./api:/code

  web:
    build: 
      context: ./web
    working_dir: /home/dev
    command: sh -c 'cd web; sh configure.sh; ./node_modules/.bin/ng serve --host 0.0.0.0'
    ports:
      - ${FRONTEND_PORT}:4200
    volumes:
      - ./:/home/dev
    depends_on:
      - api

volumes:
  psql: