# Generated by Django 5.0.6 on 2024-05-11 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkedhub', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='id',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='name',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='public',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='roadtrip',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='roadtrip',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='roadtrip',
            name='id',
        ),
        migrations.RemoveField(
            model_name='roadtrip',
            name='name',
        ),
        migrations.RemoveField(
            model_name='roadtrip',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='roadtrip',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='roadtrip',
            name='public',
        ),
        migrations.RemoveField(
            model_name='roadtrip',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='roadtrip',
            name='start_time',
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('public', models.BooleanField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='experience_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='checkedhub.experience'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roadtrip',
            name='experience_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='checkedhub.experience'),
            preserve_default=False,
        ),
    ]
