# Generated by Django 5.0.6 on 2024-05-12 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkedhub', '0003_alter_experience_end_time_alter_experience_public_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('place_id', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='airport_arrival',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='arrival_airports', to='checkedhub.place'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='airport_departure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='departure_airports', to='checkedhub.place'),
            preserve_default=False,
        ),
    ]
