# Generated by Django 5.0.6 on 2024-05-25 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkedhub', '0007_stay'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoadTrip',
            new_name='Overland',
        ),
    ]
