# Generated by Django 5.0.6 on 2024-05-25 14:51

import checkedhub.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkedhub', '0008_rename_roadtrip_overland'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='fr',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='to',
        ),
        migrations.RemoveField(
            model_name='overland',
            name='fr',
        ),
        migrations.RemoveField(
            model_name='overland',
            name='to',
        ),
        migrations.AddField(
            model_name='flight',
            name='places',
            field=checkedhub.models.PlacesOrderedManyToManyField(to='checkedhub.place'),
        ),
        migrations.AddField(
            model_name='overland',
            name='places',
            field=checkedhub.models.PlacesOrderedManyToManyField(to='checkedhub.place'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
