# Generated by Django 5.0.6 on 2024-05-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkedhub', '0009_remove_flight_fr_remove_flight_to_remove_overland_fr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='type',
        ),
        migrations.AddField(
            model_name='place',
            name='types',
            field=models.JSONField(default=[], max_length=255),
        ),
    ]
