# Generated by Django 5.0.6 on 2024-05-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkedhub', '0010_remove_place_type_place_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='types',
            field=models.JSONField(default=list, max_length=255),
        ),
    ]
