# Generated by Django 5.0.6 on 2024-05-25 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkedhub', '0011_alter_place_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='owner',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='place',
            name='owner',
        ),
    ]
