# Generated by Django 5.0.6 on 2024-05-25 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkedhub', '0012_rename_owner_experience_user_remove_place_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='user',
        ),
    ]
