# Generated by Django 5.0.6 on 2024-05-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkedhub', '0013_remove_experience_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.DecimalField(decimal_places=20, max_digits=25),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.DecimalField(decimal_places=20, max_digits=25),
        ),
    ]
